"""rename columns

Revision ID: 7f9f2e669bc0
Revises: fefe96220739
Create Date: 2026-08-25 02:26:18.294362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f9f2e669bc0"
down_revision: str | Sequence[str] | None = "fefe96220739"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("wallet_uuid", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("wallets_public_wallet_id_key"), "wallets", type_="unique")
    op.create_unique_constraint(None, "wallets", ["wallet_uuid"])
    op.drop_column("wallets", "public_wallet_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallets", sa.Column("public_wallet_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "wallets", type_="unique")
    op.create_unique_constraint(
        op.f("wallets_public_wallet_id_key"),
        "wallets",
        ["public_wallet_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("wallets", "wallet_uuid")
    # ### end Alembic commands ###
